services:
  hotel-booking.api:
    container_name: hotel-booking.api
    build:
      context: .
      dockerfile: src/HotelBookingSystem.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      - JwtOptions__AccessToken__Key=${JWT_ACCESS_KEY}
      - JwtOptions__EmailVerification__Key=${JWT_EMAIL_VERIFICATION_KEY}
      - JwtOptions__PasswordReset__Key=${JWT_PASSWORD_RESET_KEY}
      - JwtOptions__BookingConfirmation__Key=${JWT_BOOKING_CONFIRMATION_KEY}
      - SmtpOptions__Username=${SMTP_USERNAME}
      - SmtpOptions__SenderEmail=${SMTP_SENDEREMAIL}
      - SmtpOptions__Password=${SMTP_PASSWORD}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
    depends_on:
      hotel-booking.db:
        condition: service_healthy
      hotel-booking.cache:
        condition: service_healthy

  hotel-booking.db:
    container_name: hotel-booking.db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: HotelDb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d HotelDb"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  hotel-booking.cache:
    container_name: hotel-booking.cache
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  redis_data:
